//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.PolygonFederation.PolygonFederation"/> </summary
    public sealed class PolygonFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedLogin<Beamable.Polygon.Common.PolygonCloudIdentity>, Beamable.Common.ISupportsFederatedInventory<Beamable.Polygon.Common.PolygonCloudIdentity>
    {
        
        public PolygonFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "PolygonFederation";
            }
        }
    }
    
    internal sealed class MicroserviceParametersPolygonFederationClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForPolygonFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<PolygonFederationClient>();
        }
        
        public static PolygonFederationClient PolygonFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<PolygonFederationClient>();
        }
    }
}
